"""halaqa questions and answers

Revision ID: 03e7be70d2dc
Revises: a4dd37a70a1f
Create Date: 2026-07-12 02:11:03.324536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03e7be70d2dc'
down_revision: Union[str, Sequence[str], None] = 'a4dd37a70a1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('halaqa_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('halaqa_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('active_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['halaqa_id'], ['halaqas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('halaqa_id', 'active_date', name='uq_question_halaqa_date')
    )
    op.create_index(op.f('ix_halaqa_questions_id'), 'halaqa_questions', ['id'], unique=False)
    op.create_table('question_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Boolean(), nullable=False),
    sa.Column('reflection', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['halaqa_questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'user_id', name='uq_answer_question_user')
    )
    op.create_index(op.f('ix_question_answers_id'), 'question_answers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_answers_id'), table_name='question_answers')
    op.drop_table('question_answers')
    op.drop_index(op.f('ix_halaqa_questions_id'), table_name='halaqa_questions')
    op.drop_table('halaqa_questions')
    # ### end Alembic commands ###
