"""default timezone Asia/Karachi

Revision ID: ef522a020fa0
Revises: 29bb7452f172
Create Date: 2026-07-03 02:17:48.649527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef522a020fa0'
down_revision: Union[str, Sequence[str], None] = '29bb7452f172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'timezone',
               existing_type=sa.VARCHAR(),
               server_default='Asia/Karachi',
               existing_nullable=False)
    # ### end Alembic commands ###

    # data migration: move existing rows to the new default
    op.execute("UPDATE users SET timezone = 'Asia/Karachi'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'timezone',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'UTC'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###

    # lossy by design: original per-row values are not recoverable
    op.execute("UPDATE users SET timezone = 'UTC'")
